/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '[...all]': typeof import('./../src/pages/[...all].vue')['default']
    AppEchart: typeof import('./../src/components/app-echart/app-echart.vue')['default']
    AppLangSelect: typeof import('./../src/components/app-lang-select/app-lang-select.vue')['default']
    DvBorderBox1: typeof import('@kjgl77/datav-vue3')['BorderBox1']
    DvBorderBox8: typeof import('@kjgl77/datav-vue3')['BorderBox8']
    DvFullScreenContainer: typeof import('@kjgl77/datav-vue3')['FullScreenContainer']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    MyHeader: typeof import('./../src/pages/my-header/my-header.vue')['default']
    Pages: typeof import('./../src/pages/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
