/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '[...all]': typeof import('./../src/pages/[...all].vue')['default']
    AppCountUp: typeof import('./../src/components/app-count-up/app-count-up.vue')['default']
    AppEchart: typeof import('./../src/components/app-echart/app-echart.vue')['default']
    AppLangSelect: typeof import('./../src/components/app-lang-select/app-lang-select.vue')['default']
    DvBorderBox12: typeof import('@kjgl77/datav-vue3')['BorderBox12']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    MyContainer: typeof import('./../src/pages/my-container/my-container.vue')['default']
    MyHeader: typeof import('./../src/pages/my-header/my-header.vue')['default']
    Pages: typeof import('./../src/pages/index.vue')['default']
    PowerGridConstruction: typeof import('./../src/pages/power-grid-construction/power-grid-construction.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionContainer: typeof import('./../src/components/section-container/section-container.vue')['default']
    SectionHeader: typeof import('./../src/components/section-header/section-header.vue')['default']
    SocialCondition: typeof import('./../src/pages/social-condition/social-condition.vue')['default']
  }
}
