/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '[...all]': typeof import('./../src/pages/[...all].vue')['default']
    AppCountUp: typeof import('./../src/components/app-count-up/app-count-up.vue')['default']
    AppEchart: typeof import('./../src/components/app-echart/app-echart.vue')['default']
    AppLangSelect: typeof import('./../src/components/app-lang-select/app-lang-select.vue')['default']
    DvBorderBox12: typeof import('@kjgl77/datav-vue3')['BorderBox12']
    DvFullScreenContainer: typeof import('@kjgl77/datav-vue3')['FullScreenContainer']
    ElectricityUsage: typeof import('./../src/pages/electricity-usage/electricity-usage.vue')['default']
    GridReliability: typeof import('./../src/pages/grid-reliability/grid-reliability.vue')['default']
    ManagementImprovement: typeof import('./../src/pages/management-improvement/management-improvement.vue')['default']
    MyContainer: typeof import('./../src/pages/my-container/my-container.vue')['default']
    MyHeader: typeof import('./../src/pages/my-header/my-header.vue')['default']
    Pages: typeof import('./../src/pages/index.vue')['default']
    PowerGridConstruction: typeof import('./../src/pages/power-grid-construction/power-grid-construction.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesOfElectricityAndLineLoss: typeof import('./../src/pages/sales-of-electricity-and-line-loss/sales-of-electricity-and-line-loss.vue')['default']
    SectionContainer: typeof import('./../src/components/section-container/section-container.vue')['default']
    SectionHeader: typeof import('./../src/components/section-header/section-header.vue')['default']
    SocialCondition: typeof import('./../src/pages/social-condition/social-condition.vue')['default']
  }
}
